"""empty message

Revision ID: fe4ae108b4aa
Revises: 
Create Date: 2022-05-24 11:24:28.797053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4ae108b4aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('questions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'questions', ['question'])
    op.drop_constraint('category', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'])
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('category', 'questions', 'categories', ['category'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'questions', type_='unique')
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('questions', 'category_id')
    op.alter_column('categories', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
